### ISSUE TITLE
Race between & Ordering of the events

### ISSUE THREAD

**Issue by j30ng** [andreschaffer/event-sourcing-cqrs-examples#107]
Hi André. Thanks for sharing this wonderful example.

I wanted to ask your opinion on one thing.

https://github.com/andreschaffer/event-sourcing-cqrs-examples/blob/1b47ccb25791213ba0a4195d7443f59b663bd0e8/src/main/java/bankservice/service/account/AccountService.java#L70-L73

This stores the event first in the event store (which I assume is the single source of truth), and publish the event through the event bus. But if you try to scale and there are multiple instances of the application (assume now we have an external event store and and external event bus, say mongodb and kafka perhaps) each trying to store and then publish events, would that not mess up the ordering of the events?

For example say there is a race between `AccountDepositedEvent` D and `AccountWithdrawnEvent` W. What could happen is that in the event store you have D stored before W, but have D published after W through the event bus. Then application states restored through replaying event processing would not be the same as the original.

What would be your approach to solve this problem?

**Comment by j30ng** [comment]
Never mind, I overlooked the OptimisticLockingException part ;)

It shouldn't cause a problem if I can enforce the same optimistic locking mechanism when storing events in the event store.

**Comment by andreschaffer** [comment]
Hey, glad to hear you found a way forward with the examples 🙂
Cheers
